# Generated by Django 6.0 on 2026-01-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
        migrations.AlterModelTable(
            name='grape',
            table='grape',
        ),
    ]
