# Generated by Django 4.2.27 on 2026-01-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0002_alter_country_table_alter_grape_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='grape',
            name='date_last_crawled',
            field=models.DateTimeField(blank=True, help_text='Date when relationships were last searched', null=True),
        ),
    ]
