# Generated by Django 4.2.27 on 2026-01-08 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0003_grape_date_last_crawled'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrapePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL to the JPEG photo')),
                ('source', models.TextField(help_text='Photo source/attribution')),
                ('photo_type', models.CharField(choices=[('field', 'Cluster in the field'), ('laboratory', 'Cluster in the laboratory')], help_text='Type of photo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='grapes.grape')),
            ],
            options={
                'db_table': 'grape_photo',
                'ordering': ['-photo_type', 'created_at'],
            },
        ),
    ]
