# Generated by Django 4.2.27 on 2026-01-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0004_grapephoto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grapephoto',
            unique_together={('grape', 'url')},
        ),
    ]
