# Generated by Django 6.0 on 2026-01-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0005_alter_grapephoto_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='grape',
            name='species',
            field=models.CharField(blank=True, help_text='Grape species (e.g., Vitis Vinifera)', max_length=100),
        ),
    ]
