# Generated by Django 6.0 on 2026-01-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0006_grape_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='grape',
            name='breeder',
            field=models.CharField(blank=True, help_text='Name of the breeder who created the grape', max_length=200),
        ),
        migrations.AddField(
            model_name='grape',
            name='year_of_crossing',
            field=models.CharField(blank=True, help_text='Year when the grape was crossed/bred', max_length=50),
        ),
    ]
