# Generated by Django 6.0 on 2026-01-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0007_grape_breeder_grape_year_of_crossing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grapephoto',
            options={'ordering': ['photo_type', 'created_at']},
        ),
        migrations.AddField(
            model_name='grape',
            name='wikipedia_image_url',
            field=models.URLField(blank=True, help_text='URL to Wikipedia image (used as fallback when no VIVC photos exist)'),
        ),
    ]
